name: CI/CD Pipeline
on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the main branch
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Test with Maven
        run: mvn test --file pom.xml
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: target/*.jar
      - name: Build Image
        run: |
          docker build -t annnfdu/advanced_web_backend .
      - name: Login to Registry
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Image
        run: |
          docker push annnfdu/advanced_web_backend
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_NAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            docker pull annnfdu/advanced_web_backend
            docker stop zja_advanced_web_backend
            docker rm zja_advanced_web_backend
            docker run -d --name zja_advanced_web_backend -p 10086:10086 -p 10088:10088 annnfdu/advanced_web_backend

  # Docker 自动部署
#  deploy-docker:
#    needs: [build]
#    name: Deploy Docker
#    runs-on: ubuntu-latest
#    steps:
#      - name: Deploy
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }} # 服务器ip
#          username: ${{ secrets.HOST_NAME }} # 服务器登录用户名
#          password: ${{ secrets.HOST_PASSWORD }} # 服务器登录密码
#          port: ${{ secrets.HOST_PORT }} # 服务器ssh端口
#          script: |












